-- MySQL Script generated by MySQL Workbench
-- Tue Oct 18 11:06:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema example_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `example_schema` ;

-- -----------------------------------------------------
-- Schema example_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `example_schema` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `example_schema` ;

-- -----------------------------------------------------
-- Table `example_schema`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `example_schema`.`user` ;

CREATE TABLE IF NOT EXISTS `example_schema`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(255) NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `example_schema`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `example_schema`.`order` ;

CREATE TABLE IF NOT EXISTS `example_schema`.`order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `billing_address` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `is_delivered` TINYINT NULL DEFAULT 0,
  `shipping_address` VARCHAR(255) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `orders_UNIQUE` (`id` ASC) ,
  INDEX `fk_order_user_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_order_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `example_schema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `example_schema`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `example_schema`.`product` ;

CREATE TABLE IF NOT EXISTS `example_schema`.`product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(2000) NOT NULL,
  `imagesUrl` JSON NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `example_schema`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `example_schema`.`image` ;

CREATE TABLE IF NOT EXISTS `example_schema`.`image` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `imageUrl` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `example_schema`.`product_has_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `example_schema`.`product_has_image` ;

CREATE TABLE IF NOT EXISTS `example_schema`.`product_has_image` (
  `product_id` INT UNSIGNED NOT NULL,
  `image_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`product_id`, `image_id`),
  INDEX `fk_product_has_image_image1_idx` (`image_id` ASC) ,
  INDEX `fk_product_has_image_product1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_product_has_image_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `example_schema`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_image_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `example_schema`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `example_schema`.`order_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `example_schema`.`order_has_product` ;

CREATE TABLE IF NOT EXISTS `example_schema`.`order_has_product` (
  `order_id` INT UNSIGNED NOT NULL,
  `order_user_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`, `order_user_id`, `product_id`),
  INDEX `fk_order_has_product_product1_idx` (`product_id` ASC) ,
  INDEX `fk_order_has_product_order1_idx` (`order_id` ASC, `order_user_id` ASC) ,
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`order_id` , `order_user_id`)
    REFERENCES `example_schema`.`order` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `example_schema`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
