volumes:
  mysql:
  mysql_config:

services:

  mysqldb:
    image: mysql:5.7.39
    ports:
    - 3306:3306
    environment:
      # ! do not use this in production
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
      - ./database.sql:/sql/database.sql
